[package]
name = "li_ning_track_shipment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = '1'
serde_json = '1'
headless_chrome = {git = 'https://github.com/atroche/rust-headless-chrome'}